# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTM4t0cv636cgZ90P7ymcsHyrOWoPWPm
"""

import sys
from gensim.models import Word2Vec
import re

path = sys.argv[1]
corpus = []
with open(path, "r") as f:
  for line in f:
    corpus.append(line)

model = Word2Vec.load('data/w2v.model')

def most_similar_func (word):
  return model.wv.most_similar(word,topn=20)